In [ ]:
import pandas as pd

# Load the exported CSV
df = pd.read_csv("/Users/manyangtaal/Downloads/CPlusPlus.cpp/sql_project/exports/q1_seasonal_fashion_trends.csv")

# Take a peek at the data
df.head(40)

   category  season  total_sales
0     Skirt     All         6723
1     Skirt  Autumn         6268
2     Shoes     All         6130
3    Blouse  Spring         5690
4     Dress     All         5628
5     Shoes  Autumn         5240
6     Jeans  Winter         5227
7     Jeans  Spring         5226
8     Shirt     All         5188
9     Skirt  Summer         5148
10   Shorts  Summer         5014
11   Blouse     All         5011
12    Dress  Winter         4943
13   Blouse  Winter         4686
14    Shirt  Autumn         4661
15   Shorts  Spring         4625
16   Jacket     All         4583
17    Dress  Spring         4579
18   Shorts  Autumn         4498
19    Skirt  Winter         4423
20   Shorts  Winter         4401
21   Jacket  Winter         4348
22    Shoes  Spring         4345
23    Jeans  Autumn         4334
24    Shoes  Summer         4211
25   Jacket  Summer         4153
26   Shorts     All         3973
27    Shirt  Spring         3916
28    Skirt  Spring         3909
29    Shirt  Summer         3775
30    Jeans  Summer         3753
31   Blouse  Autumn         3738
32    Jeans     All         3482
33    Shoes  Winter         3366
34   Jacket  Spring         3178
35    Dress  Summer         3159
36    Shirt  Winter         3122
37   Jacket  Autumn         2967
38    Dress  Autumn         2737
39   Blouse  Summer          907

In [10]:
# Group by category + season and calculate total sales
seasonal_trends = df.groupby(["category", "season"])["total_sales"].sum().reset_index()

# Sort descending, same as ORDER BY total_sales DESC
seasonal_trends = seasonal_trends.sort_values(by="total_sales", ascending=False)

seasonal_trends.head(40)  # show top 10

   category  season  total_sales
35    Skirt     All         6723
36    Skirt  Autumn         6268
25    Shoes     All         6130
2    Blouse  Spring         5690
5     Dress     All         5628
26    Shoes  Autumn         5240
19    Jeans  Winter         5227
17    Jeans  Spring         5226
20    Shirt     All         5188
38    Skirt  Summer         5148
33   Shorts  Summer         5014
0    Blouse     All         5011
9     Dress  Winter         4943
4    Blouse  Winter         4686
21    Shirt  Autumn         4661
32   Shorts  Spring         4625
10   Jacket     All         4583
7     Dress  Spring         4579
31   Shorts  Autumn         4498
39    Skirt  Winter         4423
34   Shorts  Winter         4401
14   Jacket  Winter         4348
27    Shoes  Spring         4345
16    Jeans  Autumn         4334
28    Shoes  Summer         4211
13   Jacket  Summer         4153
30   Shorts     All         3973
22    Shirt  Spring         3916
37    Skirt  Spring         3909
23    Shirt  Summer         3775
18    Jeans  Summer         3753
1    Blouse  Autumn         3738
15    Jeans     All         3482
29    Shoes  Winter         3366
12   Jacket  Spring         3178
8     Dress  Summer         3159
24    Shirt  Winter         3122
11   Jacket  Autumn         2967
6     Dress  Autumn         2737
3    Blouse  Summer          907